
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// import Header from '@/app/header/page'
import { Toaster } from 'react-hot-toast'
import { ReduxProvider } from '@/redux/providers'
// import Header from '../components/header/header'
// import { useAppSelector } from '@/redux/store'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Billing',
  description: 'Generated by billing app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //const username = useAppSelector((state) => state.authReducer.value.username);
  return (
    <html lang="en">
      <body className="bg-gray-50 text-black">
      <ReduxProvider>
        {/* <Header /> */}
        <Toaster position="bottom-center" />
        {children}</ReduxProvider>
      </body>
    </html>
  )
}
